const SUBMIT_PERSONAL_FORM = 'SUBMIT_PERSONAL_FORM';
const SUBMIT_WALLET_FORM = 'SUBMIT_WALLET_FORM';
const REQUEST_API = 'REQUEST_API';
const SUBMIT_EXPENCES = 'REQUEST_EXPENCES';
const SUBMIT_EXCHANGES = 'REQUEST_EXCHANGES';
const RAISE_ID = 'RAISE_ID';
const REDUCE_ID = 'REDUCE_ID';

export {
  SUBMIT_PERSONAL_FORM,
  SUBMIT_WALLET_FORM,
  REQUEST_API,
  SUBMIT_EXPENCES,
  SUBMIT_EXCHANGES,
  RAISE_ID,
  REDUCE_ID,
};
