const SUBMIT_PERSONAL_FORM = 'SUBMIT_PERSONAL_FORM';
const SUBMIT_WALLET_FORM = 'SUBMIT_WALLET_FORM';
const REQUEST_API = 'REQUEST_API';
const SUBMIT_EXPENCES = 'REQUEST_EXPENCES';
const RAISE_ID = 'RAISE_ID';
const REMOVE_EXPENCES = 'REMOVE_EXPENCES';
const EDIT_EXPENCE = 'EDIT_EXPENCE';
const UPDATE_EXPENCE = 'UPDATE_EXPENCE';

export {
  SUBMIT_PERSONAL_FORM,
  SUBMIT_WALLET_FORM,
  REQUEST_API,
  SUBMIT_EXPENCES,
  RAISE_ID,
  REMOVE_EXPENCES,
  EDIT_EXPENCE,
  UPDATE_EXPENCE,
};
