const SUBMIT_PERSONAL_FORM = 'SUBMIT_PERSONAL_FORM';
const SUBMIT_WALLET_FORM = 'SUBMIT_WALLET_FORM';
const REQUEST_API = 'REQUEST_API';

export { SUBMIT_PERSONAL_FORM, SUBMIT_WALLET_FORM, REQUEST_API };
